version: "3.8"

services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bank_db}
      POSTGRES_USER: ${POSTGRES_USER:-bank_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data #data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-bank_user} -d ${POSTGRES_DB:-bank_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot
  app:
    build: .
    container_name: bank_system_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: